### ISSUE TITLE
俳句データセットの作成依頼

### ISSUE THREAD

**Issue by jumpei-T** [abegon-ta/scraping_requests#5]
### 目的
　俳句自動生成の研究をするため、俳句とそれに使われている季語のペアのデータセットを入手したい。
### 取得してほしい項目
- 俳句
- それに使われた季語
### 取得URL
- （現代俳句データベース）https://haiku-data.jp/index.php
- （一茶発句全集）https://www.janis.or.jp/users/kyodoshi/issaku.htm
- （俳句例句データベース）http://taka.no.coocan.jp/a5/cgi-bin/HAIKUreikuDB/ZOU.htm
### 備考
Webサイトは上にある方が優先順位が高いです。

**Comment by abegon-ta** [comment]
とりあえず現代俳句データベースのものから対応します。
他のものが必要になったら言ってください。

**Comment by abegon-ta** [comment]
現代俳句データベースのものから対応済み
こちらでもデータ取得しましたが、spiderは追加してあるので興味あれば自分で環境作成して動かしてもらえると

**Comment by jumpei-T** [comment]
ご対応ありがとうございます。
自分で環境作ってみます。
